default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: homies_development

test:
  <<: *default
  database: homies_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
